version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: learnflow
      POSTGRES_PASSWORD: learnflow123
      POSTGRES_DB: learnflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://learnflow:learnflow123@postgres:5432/learnflow
      REDIS_URL: redis://redis:6379
      OMNIDIM_API_KEY: ${OMNIDIM_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_WS_URL: ws://localhost:8000
      NEXT_PUBLIC_OMNIDIM_WS_URL: ${NEXT_PUBLIC_OMNIDIM_WS_URL}
    depends_on:
      - backend

volumes:
  postgres_data: